Repository gridsome/gridsome, pull requests merged in 2019-10, with the labels that each got.

#695 feat: new info command
  packages/cli/bin/gridsome.js
  packages/cli/lib/commands/info.js
  packages/cli/package.json
  yarn.lock
Labels: feature request

#284 transform-remark: front-matter parser config
  packages/transformer-remark/README.md
  packages/transformer-remark/index.js
Labels: feature request

#754 refactor: outDir to outputDir
  gridsome/lib/app/__tests__/FileProcessQueue.spec.js
  gridsome/lib/app/__tests__/ImageProcessQueue.spec.js
  gridsome/lib/app/__tests__/createRenderQueue.spec.js
  gridsome/lib/app/build/createRenderQueue.js
  gridsome/lib/app/codegen/index.js
  gridsome/lib/app/loadConfig.js
  gridsome/lib/app/queue/FileProcessQueue.js
  gridsome/lib/app/queue/ImageProcessQueue.js
  gridsome/lib/build.js
  gridsome/lib/graphql/__tests__/metadata.spec.js
  gridsome/lib/graphql/__tests__/nodes.spec.js
  gridsome/lib/plugins/RedirectsPlugin.js
  gridsome/lib/plugins/core/index.js
  gridsome/lib/serve.js
  gridsome/lib/server/Server.js
  gridsome/lib/webpack/createBaseConfig.js
  gridsome/lib/webpack/createClientConfig.js
  gridsome/lib/webpack/createServerConfig.js
  gridsome/lib/webpack/utils.js
  gridsome/lib/workers/__tests__/image-processor.spec.js
  packages/plugin-critical/index.js
  packages/plugin-sitemap/index.js
Labels: enhancement, need docs

#735 [Meta]: update bug report template
  .github/ISSUE_TEMPLATE/bug-report---.md
Labels: enhancement
